{{- $fullName := include "boundary.fullname" . }}
{{- $selectorLabels := include "boundary.selectorLabels" . }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "boundary.labels" . | nindent 4 }}
    app.kubernetes.io/component: boundary-controller
spec:
  {{- with .Values.controller.service }}
  type: {{ .type }}
  ports:
    {{- range .ports }}
    - port: {{ .number }}
      targetPort: {{ .name }}
      protocol: TCP
      name: {{ .name }}
    {{- end }}
  selector:
    {{- $selectorLabels | nindent 4 }}
    app.kubernetes.io/component: boundary-controller
  {{- end }}